---

language: python

python:
  - "2.7"

install:
  - "pip install codacy-coverage coverage pytest"

script:
  - coverage run --branch --source dotclear -m py.test -v
  - coverage report

after_success:
  - coverage xml
  - "bash <(curl -s https://codecov.io/bash)"
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then python-codacy-coverage -r coverage.xml; fi'

cache:
  pip: true

...
